gui:
  theme:
    activeBorderColor:
      - "#a6d189" # Green
      - bold
    inactiveBorderColor:
      - "#949cbb" # Overlay2
    optionsTextColor:
      - "#8caaee" # Blue
    selectedLineBgColor:
      - "#414559" # Surface0
    selectedRangeBgColor:
      - "#414559" # Surface0
    cherryPickedCommitBgColor:
      - "#ca9ee6" # Mauve
    cherryPickedCommitFgColor:
      - "#8caaee" # Blue
    unstagedChangesColor:
      - "#e78284" # Red
    defaultFgColor:
      - "#c6d0f5" # Text
    searchingActiveBorderColor:
      - "#e5c890" # Yellow
